# Generated by Django 2.1.3 on 2018-11-03 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], max_length=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('date', 'priority'),
            },
        ),
    ]
